version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: America/Los_Angeles
  target-branch: master
  reviewers:
  - nick-invision
